# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up AdoptOpenJDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Build solution with Maven
      run: mvn -B package --file pom.xml
    - name: Copy WAR file to artifacts
      run: mkdir staging && cp target/*.war staging
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging
    - name: Deploy to Azure Web App
      run: mvn deploy -Dazure.subscription=${{ secrets.AZURE_SUBSCRIPTION_ID}} -Dazure.resourcegroup=${{ secrets.AZURE_RESOURCEGROUP }} -Dazure.webapp=${{ secrets.AZURE_WEB_APP }} -Dazure.region=${{ secrets.AZURE_REGION }}
